// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtHJgsgyqiB-SRV9duwH__AQUMqJmaAE',
    appId: '1:635385895214:web:bc708199489a3c2982c2bf',
    messagingSenderId: '635385895214',
    projectId: 'auvnet-internship-assess-4af91',
    authDomain: 'auvnet-internship-assess-4af91.firebaseapp.com',
    storageBucket: 'auvnet-internship-assess-4af91.firebasestorage.app',
    measurementId: 'G-DCQ1HSL6G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY7gHo5gTDGugEs0Q877NTcyG5qJE0nXY',
    appId: '1:635385895214:android:766c5c3a9a0a978e82c2bf',
    messagingSenderId: '635385895214',
    projectId: 'auvnet-internship-assess-4af91',
    storageBucket: 'auvnet-internship-assess-4af91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmm9JhjIP3p-qCsVYWe4ifFdIRMlrXg5I',
    appId: '1:635385895214:ios:b667604763387c0d82c2bf',
    messagingSenderId: '635385895214',
    projectId: 'auvnet-internship-assess-4af91',
    storageBucket: 'auvnet-internship-assess-4af91.firebasestorage.app',
    iosBundleId: 'com.example.auvnetInternshipAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmm9JhjIP3p-qCsVYWe4ifFdIRMlrXg5I',
    appId: '1:635385895214:ios:b667604763387c0d82c2bf',
    messagingSenderId: '635385895214',
    projectId: 'auvnet-internship-assess-4af91',
    storageBucket: 'auvnet-internship-assess-4af91.firebasestorage.app',
    iosBundleId: 'com.example.auvnetInternshipAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAtHJgsgyqiB-SRV9duwH__AQUMqJmaAE',
    appId: '1:635385895214:web:b7b8f1368566f27e82c2bf',
    messagingSenderId: '635385895214',
    projectId: 'auvnet-internship-assess-4af91',
    authDomain: 'auvnet-internship-assess-4af91.firebaseapp.com',
    storageBucket: 'auvnet-internship-assess-4af91.firebasestorage.app',
    measurementId: 'G-5Z1ZMWBWTJ',
  );
}
